version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 4200:3000
    volumes:
      - ./frontend:/src
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/src
