version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 4200:3000
    volumes:
      - ./frontend:/src
      - /src/node_modules
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/src
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: on-failure
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
